import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/about.module.css'
import NavBar from '../Components/NavBar'

export default function About() {
  return (
    <>
      <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>DrugMinder</h1>
        <NavBar/>
      </main>
    </>
  )
}