import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/alcoholinfo.module.css'
import PrevButton from '../Components/PrevButton'
import NavBar from '../Components/NavBar'
import Graph from '../Components/Graph'

export default function Alcoholinfo() {
    return (
        <>
        <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <PrevButton />

        <h1 className={styles.header}>Alcohol</h1>
        <Graph/>
        <h2 className={styles.subheading}>Description</h2>
        <p clsasName={styles.content}>Cocaine is a highly addictive stimulant drug that is<br />derived from the leaves of the coca plant. Cocaine <br />works by blocking the reabsorption of dopamine</p>

        <h2 className={styles.subheading}>Effects</h2>
        <p className={styles.content}>Feelings of euphoria, happiness, and increased <br /> heartbeat <br />Pupils of the eyes dilate, making them larger <br />than normal <br /> Cocaine makes it difficult to sleep, leading to <br />insomnia</p>

        <h2 className={styles.subheading}>Precautions</h2>
        <p className={styles.content}>Only take cocaine if you are in good physical and <br />mental health<br /> Always test your cocaine before taking it <br />Stay hydrated, but dont drink too much water <br />Do not drive or operate heavy machinery while under <br /> the influence of cocaine</p>
    
        <NavBar />
        </main>

</>

    )
    }
