import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/alcoholinfo.module.css'
import PrevButton from '../Components/PrevButton'
import NavBar from '../Components/NavBar'
import Graph from '../Components/Graph'
import Link from 'next/link'

export default function Alcoholinfo() {
  return (
    <>
      <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <PrevButton />

        <h1 className={styles.header}>More Info</h1>
        <Graph />
        <h2 className={styles.header}>Statistics</h2>
        <p clsasName={styles.content}>&#8226;77% of Canadians aged 15 years or older reported<br /> consuming alcohol in the past year<br />&#8226;Alcohol is the most commonly used psychoactive<br /> substance in Canada <br />&#8226;Prevalance of heavy drinking is highest among<br /> young adults (18-24)</p>
        <hr />

        <h2 className={styles.subheading}>Seek Help</h2>
        <p className={styles.content}>
          <Link className={styles.link} href="https://www.wellnesstogether.ca/en-CA">https://www.wellnesstogether.ca/en-CA</Link>
          <br />
          <Link className={styles.link} href="https://www.drugrehab.ca/">https://www.drugrehab.ca/</Link>
          <br />
          <Link className={styles.link} href="https://canaacna.org/">https://canaacna.org/</Link>
        </p>

        <h2 className={styles.subheading}>Resources</h2>

        <Link className={styles.link} href="https://www150.statcan.gc.ca/n1/daily-quotidien/230224/dq230224a-eng.htm">https://www.statcan.gc.ca/</Link>

        <NavBar />
      </main>

    </>

  )
}
