import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/cocaineinfo.module.css'
import PrevButton from '../Components/PrevButton'
import NavBar from '../Components/NavBar'
import MoreInfo from '../Components/MoreInfo'

export default function Cocaineinfo() {
    return (

        <>
        <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <PrevButton />

        <h1 className={styles.header}>More Info</h1>
        <h3 className={styles.header}>Statistics</h3>
        <Image src="/cocainestats.png" alt="mdma" width={246} height={246} />
        <h2 className={styles.subheading}>Description</h2>
        <p clasName={styles.content}>Cocaine is a highly addictive stimulant drug that is<br />derived from the leaves of the coca plant. Cocaine <br />works by blocking the reabsorption of dopamine</p>

        <h2 className={styles.subheading}>Get Help</h2>
        <p className={styles.content}>https://www.wellnesstogether.ca/en-CA <br /> https://www.drugrehab.ca/ <br />https://canaacna.org/ </p>
        <NavBar />
        </main>
</>



    )
    }
