import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/landing.module.css'
import ButtonL from '../Components/ButtonL'


export default function Landing() {
  return (
    <>
      <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.topContainer}>
        <Image src="/logo.svg" alt="Drug Image" width={135} height={135}/>
        <div className={styles.textContainer}>
          <h1 className={styles.header}>DrugMinder</h1>
          <p className={styles.slogan}>An app of medication management, education, and empowerment.</p>
        </div>
        </div>
        <ButtonL/>
      </main>
    </>
  )
}