import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/landing.module.css'
import ButtonL from '../Components/ButtonL'


export default function Landing() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <Image src="/logo.svg" alt="Drug Image" width={135} height={135}/>
        <h1>DrugMinder</h1>
        <p>Yorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        <ButtonL/>
      </main>
    </>
  )
}