import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/mdmainfo.module.css'
import PrevButton from '../Components/PrevButton'
import NavBar from '../Components/NavBar'

export default function Mdmainfo() {
    return (

        <>
        <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>


        </main>

</>



    )
    }