import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/mdmainfo.module.css'
import PrevButton from '../Components/PrevButton'
import NavBar from "../Components/NavBar"


export default function Mdmainfo() {
  return (
        <>
        <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <PrevButton />

        <h1 className={styles.header}>More Info</h1>
        <Image src="/mdmastats.png" alt="mdmainfo" width={246} height={246} />
        <h2 className={styles.subheading}>Statistics</h2>
        <p clsasName={styles.content}>&#8226;1.7% of Canadians aged 15 years or older reported<br /> using MDMA in the past year<br />&#8226;The RCMP seized 18,000 tablets of MDMA in <br />Canada <br />&#8226;25% of users reported mixing alcohol and MDMA<br /> together</p>

        <h2 className={styles.subheading}>Seek Help</h2>
        <p className={styles.content}>https://www.wellnesstogether.ca/en-CA <br /> https://www.drugrehab.ca/ <br />https://canaacna.org/</p>

        <h2 className={styles.subheading}>Resources</h2>
        
        <a href="https://ccsa.ca/sites/default/files/2022-10/CCSA-MDMA-Ecstasy-Drug-Summary-2022-en.pdf">https://ccsa.ca/</a>
        <NavBar />  
        </main>
        </>
      )
}
