import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.module.css'
import Quiz from '../Components/Quiz'

export default function Questions() {
  return (
    <>
      <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>Step</h1>
        <Quiz/>
      </main>
    </>
  )
}
