import Head from 'next/head';
import styles from '../styles/quiz.module.css'
import Image from 'next/image'
import ButtonQ from '../Components/ButtonQ';
import NavBar from '../Components/NavBar';
import PrevButton from '../Components/PrevButton';


export default function QuizLanding() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <PrevButton/>
        <h1 className={styles.header}>Quiz</h1>
        <Image className={styles.clipboard} src="/boardicon 1.svg" alt="boardicon" width={246} height={246} />
        <h2>Ready to take quiz<br/> for you or a friend?</h2>
        <ButtonQ/>
        <NavBar/>
      </main>
    </>
  )
}
