import Head from 'next/head';
import styles from '../styles/quiz.module.css'
import Image from 'next/image'




export default function Quiz() {
    return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Image src="/boardicon 1.svg" alt="boardicon" width={246} height={246}/>
    

    <h1 >Quiz</h1>

    <h2>Ready to take quiz for you or a friend?</h2>


      
      </main>
    </>






)
}
