import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/reflection.module.css'
import ReflectionImg from '../Components/ReflectionImg'
import ButtonR from '../Components/ButtonR'


export default function Reflection() {
  return (
    <>
      <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>Reflection</h1>
        <ReflectionImg/>
        <ButtonR/>
      </main>
    </>
  )
}