import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/resources.module.css'
import NavBar from '../Components/NavBar'
import SearchBar from '../Components/SearchBar'
import ButtonRes from '../Components/ButtonRes'

export default function Resources() {
    return (
        <>
      <Head>
        <title>DrugMinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.header}>Resources</h1>
        <SearchBar/>
        <ButtonRes/>
        <NavBar/>
      </main>
    </>
    )
}